# Docs: https://squidfunk.github.io/mkdocs-material/setup/

site_name: Mycoria
site_description: Connectivity Freedom of the Original Internet
site_author: 'Mycoria Authors'

docs_dir: docs/

repo_name: 'mycoria/mycoria'
repo_url: 'https://github.com/mycoria/mycoria'

nav:
  - Introduction: index.md
  - Concept: concept.md
  - Install: install.md
  - Configure: configure.md
  - About: about.md

theme:
  name: 'material'
  font:
    text: Hind
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
    - content.code.copy
    - content.code.select
  language: en


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mycoria/mycoria

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # Code Blocks & Syntax Highlighting
  # Languages: https://pygments.org/languages/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Colored sections
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - privacy
